@startuml
scale 3
title Scraping RC Calendar For Fun And Profit
participant "Web browser" as B
participant "www.recurse.com" as S
B->S: GET /calendar
S->B: 302 to /login
B->S: GET /login
S->B: 200 with CSRF token
|||
B->S: POST /session\n(with CSRF token)
S->B: 302 /calendar
B->S: GET /calendar
S->B: 200 with the goods
@enduml
